[programs.localnet]
anchor_escrow = "BdJaXkfa1Fq3qdiatumJFLwqhs4YfYLANqNrqi81vfdo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

# for devnet
# [provider]
# cluster = "devnet"
# wallet = "~/keys/my-keypair.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
